---
- name: Update apt package cache
  tags: util
  become: "{{ util_action_become_enable }}"
  become_user: "{{ util_action_become_user|default(omit) }}"
  become_method: "{{ util_action_become_method|default(omit) }}"
  apt:
    update_cache=yes
    cache_valid_time={{ util_apt_cache_valid_time }}
