---
- name: Install local persistent data path
  tags: util
  local_action: file
    state=directory
    dest={{ util_persistent_data_path_local }}
    mode={{ util_persistent_data_path_local_mode|default(omit) }}
    owner={{ util_persistent_data_path_local_owner|default(omit) }}
    group={{ util_persistent_data_path_local_group|default(omit) }}


- name: Install remote persistent data path
  tags: util
  become: yes
  file:
    state=directory
    dest={{ util_persistent_data_path_remote }}
    owner=0
    group=0
    mode=2777
