---
- name: Install local persistent data path
  tags: util
  become: "{{ util_local_action_become_enable }}"
  become_user: "{{ util_local_action_become_user|default(omit) }}"
  become_method: "{{ util_local_action_become_method|default(omit) }}"
  local_action: file
    state=directory
    dest={{ util_persistent_data_path_local }}
    mode={{ util_persistent_data_path_local_mode|default(omit) }}
    owner={{ util_persistent_data_path_local_owner|default(omit) }}
    group={{ util_persistent_data_path_local_group|default(omit) }}


- name: Install remote persistent data path
  tags: util
  become: "{{ util_action_become_enable }}"
  become_user: "{{ util_action_become_user|default(omit) }}"
  become_method: "{{ util_action_become_method|default(omit) }}"
  file:
    state=directory
    dest={{ util_persistent_data_path_remote }}
