---
- name: Install EPEL
  tags: util
  become: "{{ util_action_become_enable }}"
  become_user: "{{ util_action_become_user|default(omit) }}"
  become_method: "{{ util_action_become_method|default(omit) }}"
  when:
    - ansible_distribution == 'CentOS'
    - util_epel_enable
  register: util_register_install_epel
  template:
    src=epel.repo.j2
    dest=/etc/yum.repos.d/epel.repo
    owner=0
    group=0
    mode=0644

- name: Update yum package cache
  tags: util
  become: "{{ util_action_become_enable }}"
  become_user: "{{ util_action_become_user|default(omit) }}"
  become_method: "{{ util_action_become_method|default(omit) }}"
  when: util_register_install_epel.changed
  command: yum
      --assumeyes
      --quiet
      makecache
